import pyautogui
import time
 
time.sleep(5)
pyautogui.press('tab')
time.sleep(.05)
pyautogui.press('tab')
time.sleep(.05)
pyautogui.press('tab')
time.sleep(.05)
pyautogui.press('tab')
time.sleep(.05)
pyautogui.press('tab')
time.sleep(.05)
pyautogui.write('malek@gmail.com')
time.sleep(.05)
pyautogui.press('tab')
time.sleep(.05)
pyautogui.write('Makmak')
time.sleep(.05)
pyautogui.press('tab')
time.sleep(.05)
pyautogui.press('enter')
time.sleep(.05)